Adding More Emojis
RishabhDevbanshi/Emojipedia pull request #38
Opened 2020-09-30 20:47 UTC by bhavesh1129

Hello!
I had added more Emoji's it would be great for me if you accept my PR as this is my first **Hacktoberfest**.
Thankyou!

2020-09-30 20:49 UTC, RishabhDevbanshi approved these changes
All Good To Go ! Will merge it by today .

2020-09-30 20:57 UTC, bhavesh1129 commented
> All Good To Go ! Will merge it by today .

Thankyou soo much!

2020-10-01 03:07 UTC, TheLearneer requested changes

2020-10-01 03:07 UTC, TheLearneer commented on src/emojipedia.js
> +        meaning: "A yellow face with scrunched eyes spewing birght-green vomit. This emoji represents illness or disgust.“."
Why add a extra “ just before the end. Also same issue with few other emojis

2020-10-01 03:07 UTC, TheLearneer commented on src/emojipedia.js
> +        meaning: "This is funny! A smiley face, rolling on the floor, laughing. The face is laughing boundlessly. The emoji version of “rofl“. Stands for „rolling on the floor, laughing“."
incorrect use of quotation mark

2020-10-01 03:07 UTC, TheLearneer commented on src/emojipedia.js
> +        meaning: "I'm the king of the world! Mr. Cool Smiley with sunglasses. Is totally self-assured and relaxed. Everything is absolutely easy and cool. Also a symbol for sun, summer holidays, and
incorrect use of quotation mark

2020-10-01 03:07 UTC, TheLearneer commented on src/emojipedia.js
> +        meaning: "A yellow face with a slight smile shown winking, usually its left eye. May signal a joke, flirtation, hidden meaning, or general positivity. Tone varies, including playful, affectio
incorrect use of quotation symbol

2020-10-01 19:47 UTC, bhavesh1129 commented
> All Good To Go ! Will merge it by today .

Hey!!
You haven't merged it yet.
P.S: A small Reminder :)

2020-10-02 10:33 UTC, bhavesh1129 reviewed
Thanks for correcting

2020-12-29 18:38 UTC, closed without merging